version: '3.8'

services:
  app:
    image: nupmanyu/ruby-sample-app:latest
    ports:
      - "4000:4000"
    restart: always
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge
