version: '3.8'

services:
  web:
    image: nupmanyu/ruby-sample-app
    container_name: ruby-sample-app
    ports:
      - "4000:4000"
    restart: always
    networks:
      - app-network
    environment:
      - RAILS_ENV=production
    deploy:
      replicas: 2  
      update_config:
        parallelism: 1  
        delay: 10s  
      rollback_config:
        parallelism: 1  
        delay: 10s 

networks:
  app-network:
    driver: bridge
